### ISSUE TITLE
Request: inidicate good affixes that should be on another item

### ISSUE THREAD

**Issue by adriaandavel** [josdemmers/Diablo4Companion#100]
Currently the app gives a red marker when a good affix is on the wrong item, could we add an orange indicator if the affix is good but should be on another item?

This could be more advanced / complicated, but that simple implementation would be very useful

**Comment by josdemmers** [comment]
That should be possible, can look into that later. Currently first some bugs/issues that I'm working on.

**Comment by josdemmers** [comment]
@adriaandavel Feature will be available in the next release.

![image](https://github.com/user-attachments/assets/3091b102-b2db-4f51-b71d-9dde3abcee29)

You can set which affixes should ignore the specified item type.
When the affix is then found on an item it's marked with a rectangle instead of a circle.

![image](https://github.com/user-attachments/assets/1937546d-73df-4af4-a0bd-4a34335775a4)

**Comment by josdemmers** [comment]
v3.8.5.0 is now released.
