### ISSUE TITLE
Aspect, Affixes and Sigils in German not working  

### ISSUE THREAD

**Issue by Dude2207** [josdemmers/Diablo4Companion#105]
When I change the language for Aspect, Affixes and Sigils to German, the frontend does not change. If I then save this, the app can no longer be started.

**Comment by josdemmers** [comment]
Thank you for the report, will check what is going on.
Seems to happen for the following languages
- German
- Spanish (LA)
- Japanese
- Portuguese
- Chinese (Traditional)

**Comment by josdemmers** [comment]
This will take longer to fix. Blizzards translation for the barb and rogue skills are the same.

The affixes in English for `Concussive` and `Concussion` for rogue and barb are `to Concussive` and `to Concussion`.
But in German both are `auf Erschütterung`. 

The app expects a unique name otherwise it cannot find the correct affix.

**Comment by josdemmers** [comment]
Fixed in v3.4.5.0
