### ISSUE TITLE
1440p SMF fr preset creation

### ISSUE THREAD

**Issue by Tifloz** [josdemmers/Diablo4Companion#109]
Hello,

I'm currently trying to create the french preset for 2k screens but even if I followed the wiki, it does not work .. 
I don't know how to debug it, is it possible to force the render of the red square in the app to quickly debug by moving values ? 

Thank you
[1440p_SMF_fr.zip](https://github.com/josdemmers/Diablo4Companion/files/15500245/1440p_SMF_fr.zip)

**Comment by josdemmers** [comment]
Hi @Tifloz what files did you change? If your naming is correct and are using SMF (HDR off, with medium font). Then you can use the `1440p_SMF_en` as the base and only replace the `1440p_SMF_fr\Tooltips\tooltip_kb_all.png". The other images are the same for each language.

The one in your zip file is still English so that is probably causing the problem.

And for the ingame settings it should help to reset your brightness to default.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/68d64e59-b6ed-4437-830e-ba3dfc5ba781)

**Comment by josdemmers** [comment]
Also an useful tip when you are debugging. You can find the following hotkey under settings:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/32a9c83f-cb86-4195-96cb-ee26a29c4587)

With the `lock screencapture` it locks your current screen. You could use it like this:
- Hover your mouse ingame over an item to show the tooltip
- Press the hotkey to lock the current screen
- Now the item tooltip will remain visible.

**Comment by Tifloz** [comment]
Ohh thanks for the quick reply ! 
I think I added the wrong file sorry :/ , after few tests I maybe forgot to update my zip file.
What I did is that I started with the `1440p_SMF_en` as base and added the missing french `shift` from the 1080p version but It does not work

Thanks a lot for the tip for debugging, before that I was like wtf how I am supposed to debug if I can't lock the screencapture xD

**Comment by josdemmers** [comment]
Added with https://github.com/josdemmers/Diablo4Companion/pull/110
