### ISSUE TITLE
language affix issue

### ISSUE THREAD

**Issue by spoter** [josdemmers/Diablo4Companion#117]
Maximum Life on Russian not found
![Screenshot 2024-10-17 202953](https://github.com/user-attachments/assets/4699533e-986f-469b-a824-9b799234860c)
![Screenshot 2024-10-17 202945](https://github.com/user-attachments/assets/75448372-ff50-4aa8-8b04-1cc59fe51cfa)

not all Affix found on russian localization. please fix and sync

**Comment by josdemmers** [comment]
That happens because the localization differs too much between some languages.
If you want to use Russian add and import the build while you have the Russian language selected.

When you switch between Russian and English afterwards you will get issues because there are too many localization differences.

**Comment by josdemmers** [comment]
Just did another test. The above only works for Maxroll builds.
D4Builds and Mobalytics will have problems with languages other than English.

This happens because the affixes `+Maximum Life` and `+% Maximum Life` are the same in English but have a different translation in some languages , for example in Russian.

Not sure yet how to solve this because the websites are in English. I'll update this issue when I have an idea how to fix this.

**Comment by josdemmers** [comment]
@spoter Found a way to convert affixes between different languages. Will be fixed in the v4.0.9.0 release.
