### ISSUE TITLE
Excessive GPU load

### ISSUE THREAD

**Issue by Remgrandt** [josdemmers/Diablo4Companion#120]
I actually see more GPU load from this tool than D4 itself. Can the sample rate be turned down? Or maybe utilize TTS like https://github.com/aeon0/d4lf instead of OCR?

**Comment by josdemmers** [comment]
Hi @Remgrandt there are multiple settings you can use to finetune the performance, depending on how you want to use the overlay.
But I think you meant the CPU load? The GPU is not used for image processing and OCR.

<img src="https://github.com/user-attachments/assets/40f84d18-c6cf-4963-9f5f-51e9108e1808" height="300">

First options are under Settings -> Overlay config -> Performance. The `Screencapture Delay` is the sample rate you are looking for. With `Scan Height` you can reduce the ROI the app uses to look for tooltips. 50 is the minimal value you need if you want to be able to detect rare items when you start leveling. 40 works if you are only interested in legendaries because those tooltips are larger.

<img src="https://github.com/user-attachments/assets/514c9940-f293-4cd9-92e1-c0fb05a38365" height="300">

The other options depend on what info you are interested in. You can use the `Affix config` and `Aspect config` to turn features on/off. For example by turning off tempered affixes if you are only interested in normal and enchanted affixes. Or turning off aspects completely if you only need affix information.

<img src="https://github.com/user-attachments/assets/5d2c8a2a-8293-4c60-8f89-df0114fcc66b" height="300">

And the app is developed with both low-, mid-, and high-end PCs in mind so you always quickly turn on/off the overlay when you start sorting your inventory using the Hotkeys config. Reducing the CPU usage to 0 when you don't need it. Then you wont experience any lag/stutters during your fights.

### TTS

Regarding TTS, has been used by other projects as well, last year there was this one. Not sure if it's still active.
https://www.reddit.com/r/diablo4/comments/14ywrwt/dbutcher_screen_reader_app_with_item_filtering/. Never used it myself but looked like it was able to read the affixes fine. You miss however some information to create an overlay.

In my companion app OCR is only a small part of the total processing. To get noticeable performance improvements I'll have to remove all image processing and only use TTS. But then you'll lose the overlay functionality of the app because you no longer know the location of the affixes. 
So it's unlikely I'll implement TTS support.

**Comment by josdemmers** [comment]
@Remgrandt Added an extra option that better controls the cpu load. Will be available in the next version, probably this weekend.

**Comment by josdemmers** [comment]
Added `Overlay update delay`, default is 5ms and is similar to the CPU usage of previous versions. You can increase the delay to lower the CPU usage.

![image](https://github.com/user-attachments/assets/ba3ced4f-e6d0-4249-96c5-13df4079c899)
