### ISSUE TITLE
Will there be a Simplified Chinese version considered in the future?

### ISSUE THREAD

**Issue by gt1226500986** [josdemmers/Diablo4Companion#27]
Now the demand of users in mainland China is particularly large, will the author consider withdrawing from the Simplified Chinese version?

**Comment by josdemmers** [comment]
Hi @gt1226500986  all languages are support. For simplified Chineses see for example: https://github.com/josdemmers/Diablo4Companion/issues/3

But so far nobody has send me a system preset that I can share.
If you want to create one yourself see the guide here:
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-create-a-new-System-Preset

If you are going to create one yourself please send it to me afterwards so that I can share it with everyone.

Let me know if you have any questions.

**Comment by gt1226500986** [comment]
![image](https:github.com/josdemmers/Diablo4Companion/assets/52158590/b6fff485-7a9e-4aa9-8134-900160d2493b)
What I mean is how to set the theme interface of the software in Chinese, I think it is only in English

**Comment by yege16888** [comment]
You can download the source code, change the text in the UI display, and then compile it yourself.

**Comment by josdemmers** [comment]
@gt1226500986 
Currently the interface is in English only. I can work on translations later but that wont be any time soon.
Would like to work on new features first.

Also if you have a working Chinese system preset please share it here so I can add it to the download manager.
Makes it a lot easier for other Chinese users.

**Comment by josdemmers** [comment]
All affixes and aspects are now translated.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/97641c41-761d-4faa-b09b-fbb878eea7dd)

**Comment by josdemmers** [comment]
@gt1226500986 Are you still interested in translating the app to Simplified Chinese?

**Comment by josdemmers** [comment]
Localization is now possible, see wiki for more info:
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-create-translations
