### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by rusagent** [josdemmers/Diablo4Companion#41]
Is it possible to help you with coding?

When hovering over the next item the dots from the previous item are still there until the new dots for the currently hovered item appear. 

Also is it possible to make the recognition a lot faster? I thought about creating multiple threads for scanning the items - and also keeping the affixes from the images in memory so they don't have to be loaded every time. Or why is it actually taking so long until the dots appear? Is the image recognition so slow?

**Comment by josdemmers** [comment]
Yes indeed, the delay is caused by the image recognition / template matching.

Feel free to clone the repo and experiment with the code. Performance improvements are welcome.
But regarding your ideas. All images used for template matching are already in memory and the template matching is done in parallel.

**Comment by josdemmers** [comment]
@rusagent 
Latest update has some great performance improvements.
To test the latest changes also enable this experimental option. Feedback is welcome!

![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/8ec43cff-aeec-41f5-bc21-14203ef2e81f)
