### ISSUE TITLE
Some affixes are incorrectly detected / displayed.

### ISSUE THREAD

**Issue by imm0r** [josdemmers/Diablo4Companion#52]
@josdemmers First of all nice idea and pretty good job so far! I have found some minor issues and wanted to let you know.

1. When ever you activate stats like damage because you want to track +Damage % you will also get positiv results for stats like "damage with xy". Sure Diablo4Companion only scans for the word "damage" when having the damage option activated but it should scan the other damage stats first which should not be displayed to correctly display those affixes that the user has activated. ![d4c_damage](https://github.com/josdemmers/Diablo4Companion/assets/7317860/16123764-ad40-46cc-a021-4d6619ec2b1b)
2. The same problem occurs with some "damage reduction" modifiers and also the "movement speed" affixes on boots (where "movement speed for" gets true while only "movement speed" is checked. ![d4c_movementspeed](https://github.com/josdemmers/Diablo4Companion/assets/7317860/153bb373-69de-4fa2-b671-687272ae4c88)

**Comment by josdemmers** [comment]
Thanks for the feedback. With the current implementation it is not really possible. Because then I would need to scan for all possible affixes. That would make everything really slow.

I'm however working on a version 2 with an improved GUI. I have some ideas to handle those issues then. No promises yet when it's ready. Still a lot to do. Hope to have it ready and tested before season 2.

**Comment by meeks726** [comment]
A workaround I found is by screenshotting my own Affix images as **_.png_** from my actual game and replacing the ones located in the preset folder I'm using (**_..\Images\1080p_SMF_en\Affixes_**).

For example, for crit dmg, this is how I have my affixes setup in Tooltips for weapons:
![image](https://github.com/josdemmers/Diablo4Companion/assets/103001939/b5d4b91e-7cf4-493b-937e-4c7b393866a0)

And this is my own affix image that I captured, to somehow differentiate it from other similar affixes:
![critical strike damage](https://github.com/josdemmers/Diablo4Companion/assets/103001939/e4145bdb-029e-4760-93e8-22d891cb9b4b)

(_Notice the extra empty space under the actual affix to differentiate it from other similar affixes or other multi-lined affixes in general_)

Unwanted crit dmg:
![image](https://github.com/josdemmers/Diablo4Companion/assets/103001939/596ee51a-850f-426f-a49c-31b8a3a0b51c)

![image](https://github.com/josdemmers/Diablo4Companion/assets/103001939/9fc014cc-0736-40e3-afb8-d4ef9dfc2ad1)

![image](https://github.com/josdemmers/Diablo4Companion/assets/103001939/c35b15f1-f607-41d8-833b-e00bba28beee)


Also works for movement speed compared to SOME of the other similar movement affixes:

![image](https://github.com/josdemmers/Diablo4Companion/assets/103001939/9d658230-00f6-42b0-af34-66ab5dbcabf2)


![image](https://github.com/josdemmers/Diablo4Companion/assets/103001939/34a624da-a789-4766-843d-f70cec8e7cb8)


This works by having 'Advanced Tooltip Information' turned on in the settings so that the game adds those extra spaces(for certain affixes that would need to continue to a new line/row) between each affixes.

Unfortunately this workaround just doesn't work for damage reduction. I just ended up excluding 'damage reduction' specifically and included the other damage reductions from the active tooltips.

**Comment by imm0r** [comment]
nice idea! now i will need to make some screenshots 🗡️

**Comment by josdemmers** [comment]
Tip to keep in mind when looking for a unique image for an affix. When capturing multiple lines the values in affixes can cause the text to have a small offset. It will no longer match in those cases.

e.g. if you have a affix with +11% or +22% it will move all text slightly to the right.

**Comment by meeks726** [comment]
> Tip to keep in mind when looking for a unique image for an affix. When capturing multiple lines the values in affixes can cause the text to have a small offset. It will no longer match in those cases.
> 
> e.g. if you have a affix with +11% or +22% it will move all text slightly to the right.

Yeah, I came across this for 'damage reduction from affected...' I ended up uploading 2 different images of the same affix; one image is the affix with a single digit %, and the other with double digit %. The spacing for any X.X% and XX.X% each both seems to be consistent.

![image](https://github.com/josdemmers/Diablo4Companion/assets/103001939/bcd7969e-7be9-441d-aa4a-54070e4cc81b)

![LOW damage reduction from affected by shadow dot](https://github.com/josdemmers/Diablo4Companion/assets/103001939/bf9b3c99-f591-44e2-94ce-18a9e4ae97aa)
![HIGH damage reduction from affected by shadow dot](https://github.com/josdemmers/Diablo4Companion/assets/103001939/08396e40-68c8-43c2-bd1e-3011b74a9431)

**Comment by meeks726** [comment]
Is it possible for the image detecting to convert the affixes found in the Tooltip into a list of strings and have it search for affixes from a dictionary?

**Comment by meeks726** [comment]
I'm assuming this affects the speed and performance drastically?

**Comment by josdemmers** [comment]
> Is it possible for the image detecting to convert the affixes found in the Tooltip into a list of strings and have it search for affixes from a dictionary?

That is possible and something I'll probably look into later.
One issue is to support all 12 Diablo languages when using OCR to convert affixes to text. With image detecting it will always work for any language.

> I'm assuming this affects the speed and performance drastically?

Will have to test that to be sure. But there are two steps that influence the performance:
- The affix image to text conversion.
- The validation part afterwards to match the text with a valid affix.

**Comment by josdemmers** [comment]
For you maybe but not everyone learned English. I'm not going to exclude those users by saying the app no longer support languages other than English.

But let's first focus on version 2.0. When everything is ready the app should be able to support multi-line affixes without using OCR.

**Comment by josdemmers** [comment]
Closing this as v2.0 is now available.

**Comment by Larsy93** [comment]
Still having this issue with Damage Reduction affixes.

**Comment by josdemmers** [comment]
> Still having this issue with Damage Reduction affixes.

Could you create a new issue with some example screenshots?
Then I can probably give some tips on how to solve this with v2.0

**Comment by Larsy93** [comment]
@josdemmers solved it by creating an image like this and setting it to the "damage reduction" affix, before it was showing damage reduction from distant and close as green when only damage reduction was selected.
![Damage Reduction 2](https://github.com/josdemmers/Diablo4Companion/assets/22322580/c468f048-1fed-49ed-bb1c-687973fcfe35)
