### ISSUE TITLE
toggle for overwritting mappings.json

### ISSUE THREAD

**Issue by Soulsuck24** [josdemmers/Diablo4Companion#57]
Is there a possibility to add a toggle to not have mappings.json overwritten when updating the images. Mostly to stop situations such as #56 where affixes get completely swapped by mistake and that sort of thing.

**Comment by josdemmers** [comment]
Currently on vacation with limited / no Internet most of the time. Will be back in two weeks, around 15-10.

**Comment by josdemmers** [comment]
Added backup functionality, will try to release it later today.
Will also merged system preset changes I received in the last two weeks.

Problems like this should happen less and less when the affix mappings are getting closer to 100%.

**Comment by josdemmers** [comment]
Toggle not possible for now because the complete preset archive is extracted at once.
Also everyone should be on the latest mappings file.
However to prevent issues there is now (see v2.1.3) a backup of the mappings file in case something goes wrong.

The pull request with your fix is merged into master.
