### ISSUE TITLE
Damage reduction affix issue

### ISSUE THREAD

**Issue by Larsy93** [josdemmers/Diablo4Companion#58]
@josdemmers Selecting the damage reduction affix shows as green on distant and close enemies affix as well, solved it by changing the damage reduction image to this with blank space below, any other better/easier ways to fix this? 1440p preset
![Damage Reduction 2](https://github.com/josdemmers/Diablo4Companion/assets/22322580/48079055-c586-428c-af4e-3733370398fc)

**Comment by Larsy93** [comment]
Thanks! thats a clever way of fixing it, will try and report back.

**Comment by josdemmers** [comment]
You are missing a dot, one of the affixes is not detected.
It uses the dots to look for affixes. Because one is missing it does something like this:
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/fba6a267-7909-4fd0-a07b-d049cba76bad)

Because of that it's green because it finds `damage reduction`

**Comment by josdemmers** [comment]
You can try creating your own `dot-affixes_1.png` or you can go to `Debug` and change the threshold.
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/47a55da8-e801-4ede-8e7e-dde18266b1e8)

Default is 0.05, you could try if 0.06/0.07 works for you.
