### ISSUE TITLE
Missing movement speed after killing elite

### ISSUE THREAD

**Issue by Soulsuck24** [josdemmers/Diablo4Companion#60]
I believe it was in an older version but has since gone missing. Was planning to set it as red to differentiate from base move speed but was unable to locate it.

**Comment by josdemmers** [comment]
Thank you, I'm aware of a few affixes that are missing since the 2.0 update.
I parse an affix list from the game data since v2.0 but it misses a few affixes.
It's on my todo list to improve the parser, but good to have it now listed as an issue as well.

So far the following have been reported as missing:
- Damage for 4 seconds after killing an elite
- Evade grants +30% movement speed for 1 second
- Movement speed for 4 seconds after killing an elite

**Comment by josdemmers** [comment]
Fixed in v2.2.2.0
