### ISSUE TITLE
The red rectangle does not appear

### ISSUE THREAD

**Issue by PipoGelido** [josdemmers/Diablo4Companion#80]
![Screenshot 2024-01-28 230441](https://github.com/josdemmers/Diablo4Companion/assets/157997329/d79964f3-fa81-41b2-bc0b-a5c27ad815d5)

**Comment by josdemmers** [comment]
Hi @PipoGelido which system preset are you using? 1440p_SMF_en? or one of the HDR presets?
And what ingame settings are you using? Your color scheme looks rather odd, text that should be orange is almost yellow.

**Comment by PipoGelido** [comment]
I'm using 1440p_HMF_en and I'm using HDR in game, I tried also to use 1440p_SMF_en and SDR but doesn't work either.

**Comment by josdemmers** [comment]
Don't have an HDR monitor myself but from what hear from others it can be more difficult to setup because of the differences in color.
Also turning off HDR ingame is not always enough because it can still be active in your monitor settings.

But let's try to get HDR working for you. That should work as well.
The HDR preset 1440p_HMF_en is not used by a lot of users. I'm not sure the recommended settings are correct.
The other HDR preset (2160p_HSF_en) recommends 100/255 for the app brightness threshold settings.

Could you set the min threshold to 100 and check if that works for you? The max threshold is already set to 255 by default.

![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/840b36ce-0fb5-4cdc-958b-1267ab2513cb)

**Comment by josdemmers** [comment]
Another option that will always work is to create your own system preset specific for your HDR/Monitor configuration:
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-create-a-new-System-Preset

But then you will have to collect all affixes/aspects yourself. So it's better and less work for you if you could get one of the existing system presets to work.

**Comment by PipoGelido** [comment]
![Screenshot 2024-01-29 165526](https://github.com/josdemmers/Diablo4Companion/assets/157997329/e9f1ca57-03fd-46d4-92ec-d200d870696a)
![immagine](https://github.com/josdemmers/Diablo4Companion/assets/157997329/e6545344-a573-4097-8838-0b0d4311238e)
![immagine](https://github.com/josdemmers/Diablo4Companion/assets/157997329/92939ade-7ee0-42c7-a04a-89112cfd6f7d)
![immagine](https://github.com/josdemmers/Diablo4Companion/assets/157997329/1b485495-b5c4-4218-8440-ae48632207ef)
I think that I need to create my own :(
It doens't work with both hdr on d4 and monitor turned off, and 1440p_SMF_en
![immagine](https://github.com/josdemmers/Diablo4Companion/assets/157997329/17836071-c483-4431-bf86-0adbc2655887)

**Comment by josdemmers** [comment]
Looks like you changed your language in your last test. Could you set it back to English and test again?
The app looks for this image to find the location of the tooltip
![tooltip_kb_all](https://github.com/josdemmers/Diablo4Companion/assets/8627157/9aab8fb0-b6a2-4052-8250-fbde840586f8)

**Comment by josdemmers** [comment]
Also the last image is with HDR turned off? That looks almost correct for the `1440p_SMF_en` preset, we should be able to get that working.
I think your brightness setting ingame is too dark here. Try the following ingame setting and set the app brightness setting back to 60/255
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/8b1fabc6-c906-4f35-be80-d3208c04aafd)

**Comment by josdemmers** [comment]
Just to be sure the preset was downloaded correctly.
Does your preset folder looks like this?
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/07d82748-e4e0-4086-9977-ac2d2f03eaf7)

**Comment by PipoGelido** [comment]
![immagine](https://github.com/josdemmers/Diablo4Companion/assets/157997329/55efde34-f2f7-4db7-a704-cabefc7653a6)
yep

**Comment by josdemmers** [comment]
And what about this ingame setting?
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/76d66af0-c499-4ad6-968c-8d087f13dd5d)

**Comment by PipoGelido** [comment]
Same

**Comment by josdemmers** [comment]
Then try replacing this image with your own:
`\Images\1440p_SMF_en\Tooltips\tooltip_kb_all.png`

Easiest way to that is pressing `Shift+Windows+S` and then capture the Shift key icon ingame.

Restart the app after replacing the image.

**Comment by PipoGelido** [comment]
It works <3, to create a preset from 0 can I create a new folder and insert in it the files or do I need to use an existing one and change it? I'm italian, can I name the affixes in italian or I need to use a specific id in english? Like "trap skill cooldown reduction.png"

**Comment by josdemmers** [comment]
Depending on the configuration you want to use you get something like this:
`1440p_SMF_it`

- 1440p
- SDR
- Medium Font

There's a `Naming convention` section on this page that explains the name of the folder:
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-create-a-new-System-Preset

Because you needed to replace `tooltip_kb_all.png` before it worked I don't think you should use an existing one. Better to create a preset from 0.

Only the folders and names in the `folder structure` section matter.
https://github.com/josdemmers/Diablo4Companion/wiki/How-to-create-a-new-System-Preset#folder-structure

All images in `affixes` and `aspect` do not matter. You can use any name you want.
So for example `trap skill cooldown reduction.png` will also work if you name it `Pipo.png`

**Comment by josdemmers** [comment]
No problem, glad we have finally have something working. Good luck with creating the system preset.
If you have questions you can also join Discord.

**Comment by PipoGelido** [comment]
:)
