### ISSUE TITLE
Not importing stat priorities from Maxroll

### ISSUE THREAD

**Issue by smoochy** [josdemmers/Diablo4Companion#93]
Heya,

Just wanted to prepare for Season 4 and imported a build from Maxroll. Unfortunately, the stat priorities for the different items are not imported. Only the aspects.

I followed the [guide](https://github.com/josdemmers/Diablo4Companion/wiki/How-to-import-and-export-builds) on how to import. Imported 3 different build variants. For each, the according aspects are imported.

I took the Planner from [this Maxroll Guide](https://maxroll.gg/d4/build-guides/minion-necromancer-guide). The PlannerID is `cm6pf0xa`.

Not sure, if this is related to your app, or [Maxroll D4 Scraper](https://github.com/danparizher/maxroll-d4-scraper).

Kind Regards,
smoo

**Comment by josdemmers** [comment]
Hi @smoochy that D4 scraper is no longer used. It stopped working earlier in season 3 when the website layout changed.
My app now has it's own Maxroll import, but that's currently broken as well because of all the affix changes for season 4.

The current version is still based on season 3 and doesn't have the new affixes. I'm preparing a new version based on the PTR data. It's almost ready for release. Was planning to release it tomorrow otherwise it causes problems for those still playing season 3.

**Comment by josdemmers** [comment]
You can follow the season 4 progress here:
https://github.com/josdemmers/Diablo4Companion/tree/season4

**Comment by smoochy** [comment]
Thanks for the information. I was assuming that it was related to the new Affix system. 


Is it correct that nobody yet created a preset for 1440p, SDR with small fonts? 

Then in the coming days I will try to do it with the instructions. I don't like the medium font, but unfortunately don't have an HDR display.

**Comment by josdemmers** [comment]
Yes, correct. Only 1440p_HSF_en and 1440p_SMF_en.
But 1440p_SSF_en should be easy to create. I think you can just copy 1440p_SMF_en and only replace the `tooltip_kb_all.png` image.

**Comment by josdemmers** [comment]
![image](https://github.com/josdemmers/Diablo4Companion/assets/8627157/feedbb8f-b514-4188-bc43-b86f46e2738f)
